integrating with other libs translated
reactjs/fa.react.dev pull request #193
Opened 2021-01-11 08:31 UTC by hosseinAMD

`Integrating with other libraries` translation has been completed.
It was one of the most difficult pages because of English concepts used in it.

In order to transfer information and saving originality of contents I haven't changed anything and directly translated.

Anyway, Take your time to review it.
Thanks.

2021-01-24 17:29 UTC, sorousht commented
@hosseinAMD Thanks, I'll review it soon. Sorry if you have waited for a long time.

2021-03-10 05:28 UTC, seven-deuce requested changes
بخش اول اصلاحات

2021-03-10 07:20 UTC, seven-deuce requested changes
سلام @hosseinAMD 
ممنون از ترجمه خوبتان 
صفحه ی سنگینی بود و من ویرایش های لازم را انجام دادم. لطفا آن ها را مرور کرده و آپدیت کنید تا در قدم بعد آنها را نهایی کنیم. ممنون

2021-03-10 07:20 UTC, seven-deuce commented on content/docs/integrating-with-other-libraries.md
> +آگاهی کامپوننت‌های ری‌اکت شما از مدل‌ها و کالکشن‌های Backbone نیاز روش بالا است. اگر شما بعدا برنامه مهاجرت به یک راهکار مدیریت داده دیگر را داشته‌باشید، ممکن است بخواهید اطلاعات مربوط به Backbone را
شیوه‌ی توضیح داده شده در بالا، نیازمند آن است که کامپوننت‌های ری‌اکت از کالکشن‌ها و مدل‌های Backbone مطلع باشند.  اگر شما بعدا برنامه مهاجرت به یک راهکار مدیریت داده دیگر را داشته ‌باشید، ممکن است ترجیح دهید که اطلاعات مربوط به Backbone را در بخش‌های کمی از کد متمرکز کنید.

2021-03-10 07:20 UTC, seven-deuce commented on content/docs/integrating-with-other-libraries.md
> +راهکار ما برای این مورد استخراج صفت‌های مدل به عنوان یک داده خام در هنگام تغییر کدن آن و حفظ منطق در یک مکان می‌باشد. این [یک کامپونت مرتبه بالا](/docs/higher-order-components.html) می‌باشد که تمام ص
یک راهکار برای این مورد استخراج صفت‌های مدل به شکل داده‌ی خام در هنگام تغییرات و حفظ تمام منطق در یک مکان می‌باشد. این [یک کامپونت مرتبه بالا](/docs/higher-order-components.html) می‌باشد که تمام صفت‌های یک مدل Backbone را در state استخراج می‌کند و داده را به کامپوننت پوشش داده شده ارسال می‌کند.

2021-03-10 07:20 UTC, seven-deuce commented on content/docs/integrating-with-other-libraries.md
> +با این راه، تنها کامپوننت مرتبه بالا نیاز به دانستن مدل‌های داخلی Backbone دارد و بیشتر قسمت‌های اپ می‌توانند از Backbone دور بمانند.
با این شکل، تنها کامپوننت مرتبه بالا نیاز به دانستن مدل‌های داخلی Backbone را دارد و بیشتر قسمت‌های اپ می‌توانند نسبت به Backbone بی‌تفاوت باقی بمانند.

2021-03-10 07:20 UTC, seven-deuce commented on content/docs/integrating-with-other-libraries.md
> +در مثال زیر، برای شکل دادن اولیه state یک کپی از صفت‌های مدل ایجاد می‌کنیم. ما در رویداد `change` subscribe می‌کنیم (و هنگام نابودی unsubscribe می‌کنیم) و زمانی که تغییر اتفاق افتاد، ما state را با ص
در مثال زیر، برای ساختن state اولیه، یک کپی از صفت‌های مدل ایجاد می‌کنیم. ما در رویداد `change` subscribe می‌کنیم (و هنگام نابودی unsubscribe می‌کنیم) و زمانی که تغییر اتفاق افتاد، ما state را با صفت‌های جدید مدل به‌روزرسانی می‌کنیم. در نهایت، مطمئن می‌شویم که اگر prop خود `model` تغییر کرد، حتما از مدل قدیمی unsubscribe می‌کنیم و به مدل جدید subscribe کنیم.

2021-03-10 07:20 UTC, seven-deuce commented on content/docs/integrating-with-other-libraries.md
> +در نظر داشته باشید که این مثال قرار نیست با کار کردن با Backbone طاقت فرسا باشد اما باید به شما ایده چگونه انجام دادن این راه را بدهد:
در نظر داشته باشید که این مثال قرار نیست کار کردن با Backbone را به شکل مبسوط نشان دهد، اما باید به شما ایده چگونه انجام دادن این راه را بدهد:

2021-03-10 07:20 UTC, seven-deuce commented on content/docs/integrating-with-other-libraries.md
> +برای آن که نشان دهیم چگونه از آن استفاده کنید، یک کامپوننت ری‌اکت `NameInput` به یک مدل Backbone متصل خواهیم کرد و صفت `firstName` آن را با هر تغییر ورودی به‌روز می‌کنیم:
برای آن که نشان دهیم چگونه از آن استفاده کنید، یک کامپوننت ری‌اکت `NameInput` را به یک مدل Backbone متصل خواهیم کرد و صفت `firstName` آن را با هر تغییر ورودی به‌روز می‌کنیم:

2021-03-10 07:20 UTC, seven-deuce commented on content/docs/integrating-with-other-libraries.md
> +این تکنیک محدود به Backbone نیست. شما می‌تونید با subscribe کردن تغییرات در هر کتابخانه مدل در متدهای چرخه‌حیات و به صورت اختیاری کپی کردن داده در state محلی ری‌اکت از آن استفاده کنید.
این تکنیک محدود به Backbone  نیست. شما می‌توانید با subscribe کردن به تغییرات در هر کتابخانه مدلی، در متدهای چرخه‌حیات، به صورت اختیاری داده را به state  درونی ری‌اکت کپی کرده و از آن استفاده کنید.

2023-09-27 19:25 UTC, rezvani2647 commented
I close this PR due to this file path does not exist in new website.

2023-09-27 19:25 UTC, closed without merging