Editor Setup
reactjs/fa.react.dev pull request #365
Opened 2023-09-29 17:07 UTC by Jam-Hejrati

translate editor-setup to persian

2023-09-29 17:24 UTC, rezvani2647 commented
Greate. Thank you for your time and effort.
but there is a slitly change you need to apply before we review you PR.
Please read [Style Guid](https://github.com/reactjs/fa.react.dev/blob/main/STYLE-GUIDE.md) and make sure your translation meets the style guid standards. (for example remove all `div` tags).

Thank you.

2023-09-29 18:28 UTC, Jam-Hejrati commented
Thanks for guidance.
I attempted for fixing issues according to (Style Guide) [https://github.com/reactjs/fa.react.dev/blob/main/STYLE-GUIDE.md]

2023-09-29 18:29 UTC, Jam-Hejrati commented
Thanks for guidance
I attempted to fix and delete redundant tags according to (Style Guide) [https://github.com/reactjs/fa.react.dev/blob/main/STYLE-GUIDE.md]

2023-09-29 18:29 UTC, Jam-Hejrati commented
Thanks for guidance
I attempted to fix and delete redundant tags according to Style Guide

2023-10-17 07:58 UTC, Jam-Hejrati commented
Hi @rezvani2647 
Why did the deployment check fail?
I can't see any detail of checks for failed reason to fix it.

2023-10-31 05:03 UTC, faeghe-hajiabadi requested changes

2023-10-31 05:03 UTC, faeghe-hajiabadi commented on src/content/learn/editor-setup.md
> +بعضی ویرایشگرها به صورت داخلی این قابلیت ها را دارند، اما بعضی دیگر نیاز به اضافه کردن افزونه هستند. بررسی کنید تا ببینید ویرایشگر انتخابی شما چه پشتیبانی ارائه می‌دهد تا مطمئن شوید!
املای مطمئن درست نوشته نشده است.

2023-11-14 06:54 UTC, faeghe-hajiabadi approved these changes

2024-02-17 07:21 UTC, rezvani2647 approved these changes

2024-02-17 14:32 UTC, merged